<?php include '_header.php';?>
        <div class="main_col">
            <?php include '_leftcol.php';?>    
            <div class="right_col">
                <?php include '_breadcrumb.php';?>
                <div class="con_block">
                    <h3 class="con_title">商品API</h3>
                    <div class="con_main">
                      <h4 class="con_main_title">修改商品資訊</h4>
                      <h5 class="con_main_sub_title">用途</h5>
                      <p>購物平台透過自定的商品料號來指定商品，修改uitox系統商品資訊。</p>
                      <h5 class="con_main_sub_title">串接方式</h5>
                      <p>採https網路協定，以POST方式串接實作。URL路徑提供如下：<br/>https://[uitox server name]/show_upd/set_item_by_sup</p>
                      <h5 class="con_main_sub_title">輸入參數、範例及說明</h5>
                      <p>HTTPS POST參數整理如下：</p>
                      <table class="con_table">
                            <thead>
                              <tr>
                                  <th>參數</th>
                                  <th>說明</th>
                                  <th>型別</th>
                                  <th>限制</th>
                                  <th>屬性</th>
                                  <th>備註</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>version</td>
                                    <td>版本</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>此API版本請填入1.0.0</td>
                                 </tr>
                                <tr>
                                    <td>client_id</td>
                                    <td>帳號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請聯繫uitox人員提供</td>
                                 </tr>
                                <tr>
                                    <td>token</td>
                                    <td>密碼</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請聯繫uitox人員提供</td>
                                 </tr>
                                <tr>
                                    <td>platform_id</td>
                                    <td>uitox平台編號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請聯繫uitox人員提供</td>
                                 </tr>
                                <tr>
                                    <td>cv</td>
                                    <td>檢查碼</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請參考檢查碼章節</td>
                                 </tr>
                                <tr>
                                    <td>data</td>
                                    <td>API參數字串</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請聯繫uitox人員提供</td>
                                 </tr>
                            </tbody>
                         </table>
                         <p>請參考以下JSON字串範例：</p>
                          <code>
                            { <br/>
                              &nbsp;&nbsp;"client_id":"uitoxbeta",<br/>
                              &nbsp;&nbsp;"token":"qWerAsdf",<br/>
                              &nbsp;&nbsp;"platform_id":"AW000001",<br/>
                              &nbsp;&nbsp;"version":"1.0.0",<br/>
                              &nbsp;&nbsp;"cv":"0b139084d4aedcaaaeaf5047bae9b90b135e69041e446aa6d0ee0fa23f94ee2b",<br/>
                            }
                          </code>
                          <p>在 data 參數值這串 JSON 字串內，各參數說明如下：</p>
                          <table class="con_table">
                            <thead>
                              <tr>
                                  <th>參數</th>
                                  <th>說明</th>
                                  <th>型別</th>
                                  <th>限制</th>
                                  <th>屬性</th>
                                  <th>備註</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>count</td>
                                    <td>修改總筆數</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請參考以下代碼表</td>
                                 </tr>
                                <tr>
                                    <td>type</td>
                                    <td>處理型態</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>1: uitox 商品 id<br/>2: 廠商自用料號</td>
                                 </tr>
                                <tr>
                                    <td>request_data/uitox_supplier_id</td>
                                    <td>uitox廠商編號</td>
                                    <td>String</td>
                                    <td>6</td>
                                    <td>必填</td>
                                    <td>查詢欄位</td>
                                 </tr>
                                <tr>
                                    <td>request_data/product_id</td>
                                    <td>商品 ID</td>
                                    <td>String</td>
                                    <td>40</td>
                                    <td>必填</td>
                                    <td>type = 1 時帶入uitox 商品 ID, type =2 時帶入廠商自用料號</td>
                                 </tr>
                                <tr>
                                    <td>expires_on</td>
                                    <td>查詢時間</td>
                                    <td>String</td>
                                    <td>6</td>
                                    <td>必填</td>
                                    <td>格式HH:MM:SS</td>
                                 </tr>
                                <tr>
                                    <td>request_data/product_name</td>
                                    <td>商品名稱</td>
                                    <td>String</td>
                                    <td>255</td>
                                    <td>必填</td>
                                    <td>有傳入時不能為空 / 有多規格時同步更新</td>
                                 </tr>
                                <tr>
                                    <td>request_data/show_name</td>
                                    <td>賣場名稱</td>
                                    <td>String</td>
                                    <td>255</td>
                                    <td>必填</td>
                                    <td>有傳入時不能為空 / 有多規格時同步更新</td>
                                 </tr>
                                <tr>
                                    <td>request_data/product_name</td>
                                    <td>商品名稱</td>
                                    <td>String</td>
                                    <td>255</td>
                                    <td>必填</td>
                                    <td>有傳入時不能為空 / 有多規格時同步更新</td>
                                 </tr>
                                <tr>
                                    <td>request_data/spec/list/main_picture</td>
                                    <td>主圖名稱 (對應名稱)</td>
                                    <td>String</td>
                                    <td>20</td>
                                    <td>非必填</td>
                                    <td>只需檔名</td>
                                 </tr>
                                <tr>
                                    <td>request_data/spec/list/color</td>
                                    <td>顏色</td>
                                    <td>String</td>
                                    <td>20</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/spec/list/size</td>
                                    <td>尺寸</td>
                                    <td>String</td>
                                    <td>20</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/spec/list/max_sale_qty</td>
                                    <td>eShop設定最大銷售量</td>
                                    <td>Number</td>
                                    <td>5</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/spec/list/production_location</td>
                                    <td>產地</td>
                                    <td>String</td>
                                    <td>25</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/spec/list/sell_oversea</td>
                                    <td>是否賣海外 (Y/N)</td>
                                    <td>String</td>
                                    <td>41</td>
                                    <td>非必填</td>
                                    <td>預設 Y',Y': 是'N': 否<td>
                                 </tr>
                                <tr>
                                    <td>request_data/descript/picture</td>
                                    <td>文案圖名稱 (對應名稱)</td>
                                    <td>String</td>
                                    <td>20</td>
                                    <td>非必填</td>
                                    <td>只需檔名; 多張 ( <= 20)<td>
                                 </tr>
                                <tr>
                                    <td>request_data/descript/slogan</td>
                                    <td>賣點</td>
                                    <td>String</td>
                                    <td>85</td>
                                    <td>非必填</td>
                                    <td>1~5<td>
                                 </tr>
                                <tr>
                                    <td>request_data/descript/need_space</td>
                                    <td>文案間是否有間隙</td>
                                    <td>String</td>
                                    <td>1</td>
                                    <td>非必填</td>
                                    <td>文案之間是否要有間隙<br/>Y: 要<br/>N: 不需要<td>
                                 </tr>
                                <tr>
                                    <td>request_data/warranty_date/year</td>
                                    <td>保固期限 (幾年)</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/warranty_date/month</td>
                                    <td>保固期限 (幾個月)</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/service/website</td>
                                    <td>維修網址</td>
                                    <td>String</td>
                                    <td>85</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/service/address</td>
                                    <td>維修地址</td>
                                    <td>String</td>
                                    <td>85</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/service/tel</td>
                                    <td>維修電話</td>
                                    <td>String</td>
                                    <td>85</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/own_custom_no</td>
                                    <td>eShop廠商自訂欄位</td>
                                    <td>String</td>
                                    <td>40</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/spec_note</td>
                                    <td>規格說明</td>
                                    <td>String</td>
                                    <td>4000</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/equip_note</td>
                                    <td>配備</td>
                                    <td>String</td>
                                    <td>4000</td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/box_num</td>
                                    <td>箱入數</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                                <tr>
                                    <td>request_data/min_incoming_stock</td>
                                    <td>最小進貨量</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td>非必填</td>
                                    <td><td>
                                 </tr>
                            </tbody>
                         </table>
                         <h5 class="con_main_sub_title">輸出回應、範例及說明</h5>
                         <p>API輸出回應的資料，一律放置在HTTPS協定回應結果的BODY區域，同樣以JSON格式輸出，請參考以下範例。</p>
                         <code>
                            { <br/>
                              &nbsp;&nbsp;"status_code":100,<br/>
                              &nbsp;&nbsp;"query_date":"2015/07/07",<br/>
                              &nbsp;&nbsp;"query_time":"12:00:00",<br/>
                              &nbsp;&nbsp;"count":3,<br/>
                              &nbsp;&nbsp;"failure":0,<br/>
                              &nbsp;&nbsp;"success":3,<br/>
                              &nbsp;&nbsp;"respone":<br/>
                            }
                          </code>
                          <p>在API輸出回應的這串JSON字串內，各參數說明如下</p>
                         <table class="con_table">
                            <thead>
                              <tr>
                                  <th>參數</th>
                                  <th>說明</th>
                                  <th>型別</th>
                                  <th>限制</th>
                                  <th>屬性</th>
                                  <th>備註</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>status_code</td>
                                    <td>狀態</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td>請參考以下代碼表</td>
                                 </tr>
                                <tr>
                                    <td>query_Date</td>
                                    <td>新增日期 yyyymmdd</td>
                                    <td>DateTime</td>
                                    <td></td>
                                    <td></td>
                                    <td>依照平台時間時區回覆</td>
                                 </tr>
                                <tr>
                                    <td>query_time</td>
                                    <td>新增時間hhmmss</td>
                                    <td>DateTime</td>
                                    <td></td>
                                    <td></td>
                                    <td>依照平台時間時區回覆</td>
                                 </tr>
                                <tr>
                                    <td>count</td>
                                    <td>新增總筆數</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>success</td>
                                    <td>成功筆數</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>failure</td>
                                    <td>失敗筆數</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/drc</td>
                                    <td>細項回應狀態</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/uitox_spec_id</td>
                                    <td>Uitox 規格編號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/supplier_spec_id</td>
                                    <td>廠商自訂規格編號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/uitox_spec_id</td>
                                    <td>Uitox 規格編號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/spec/uitox_product_id</td>
                                    <td>uitox商品ID</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td>範例：201411AG12000001</td>
                                 </tr>
                                <tr>
                                    <td>respone/spec/own_product_id</td>
                                    <td>eShop廠商自用料號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                            </tbody>
                         </table>
                         <h5 class="con_main_sub_title">使用建議</h5>
                         <p>一次執行最多100筆紀錄</p>
                         <h5 class="con_main_sub_title">代碼說明</h5>
                         <p>status_code參數</p>
                         <table class="con_table">
                            <thead>
                              <tr>
                                  <th>代碼</th>
                                  <th>說明</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>4002001100</td>
                                    <td>程式執行成功</td>
                                 </tr>
                                <tr>
                                    <td>4002001199</td>
                                    <td>筆數不符</td>
                                 </tr>
                                <tr>
                                    <td>4002001200</td>
                                    <td>傳入參數錯誤</td>
                                 </tr>
                                <tr>
                                    <td>4002001201</td>
                                    <td>傳入參數錯誤</td>
                                 </tr>
                                <tr>
                                    <td>4002001201</td>
                                    <td>傳入參數錯誤</td>
                                 </tr>
                                <tr>
                                    <td>4002001202</td>
                                    <td>傳入參數為空值</td>
                                 </tr>
                                <tr>
                                    <td>4002001203</td>
                                    <td>傳入參數型態錯誤</td>
                                 </tr>
                                <tr>
                                    <td>4002001204</td>
                                    <td>傳入參數長度錯誤</td>
                                 </tr>
                            </tbody>
                         </table>
                         <p>drc參數</p>
                         <table class="con_table">
                            <thead>
                              <tr>
                                  <th>代碼</th>
                                  <th>說明</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>100</td>
                                    <td>新增成功</td>
                                 </tr>
                                <tr>
                                    <td>199</td>
                                    <td>筆數不符合</td>
                                 </tr>
                                <tr>
                                    <td>201</td>
                                    <td>傳入API的參數錯誤</td>
                                 </tr>
                                <tr>
                                    <td>202</td>
                                    <td>傳入API的參數為空值</td>
                                 </tr>
                                <tr>
                                    <td>203</td>
                                    <td>傳入參數型態錯誤</td>
                                 </tr>
                                <tr>
                                    <td>204</td>
                                    <td>204 傳入參數長度錯誤</td>
                                 </tr>
                                <tr>
                                    <td>205</td>
                                    <td>品名必須一致</td>
                                 </tr>
                                <tr>
                                    <td>206</td>
                                    <td>保險價值必須一致</td>
                                 </tr>
                                <tr>
                                    <td>207</td>
                                    <td>廠商編號必須一致</td>
                                 </tr>
                                <tr>
                                    <td>208</td>
                                    <td>顏色/尺寸名稱不可重複</td>
                                 </tr>
                                <tr>
                                    <td>209</td>
                                    <td>多規格必須填寫顏色</td>
                                 </tr>
                                 <tr>
                                    <td>210</td>
                                    <td>每列必須填寫尺寸</td>
                                 </tr>
                                 <tr>
                                    <td>211</td>
                                    <td>每列必須填寫廠商自用料號</td>
                                 </tr>
                                 <tr>
                                    <td>212</td>
                                    <td>無廠商合約資訊</td>
                                 </tr>
                                 <tr>
                                    <td>213</td>
                                    <td>廠商自用料號必填</td>
                                 </tr>
                                 <tr>
                                    <td>214</td>
                                    <td>廠商自用料號重複</td>
                                 </tr>
                                 <tr>
                                    <td>215</td>
                                    <td>廠商自用料號格式錯誤</td>
                                 </tr>
                                 <tr>
                                    <td>216</td>
                                    <td>廠商自用欄位格式錯誤</td>
                                 </tr>
                                 <tr>
                                    <td>217</td>
                                    <td>特賣變價中，無法新增顏色/尺寸</td>
                                 </tr>
                                 <tr>
                                    <td>218</td>
                                    <td>圖片產生失敗</td>
                                 </tr>
                                 <tr>
                                    <td>219</td>
                                    <td>切圖失敗</td>
                                 </tr>
                                 <tr>
                                    <td>220</td>
                                    <td>新增失敗</td>
                                 </tr>
                            </tbody>
                         </table>
                    </div>
                </div>
            </div>
        </div>
<?php include '_footer.php';?>