<?php include '_header.php';?>
        <div class="main_col">
            <?php include '_leftcol.php';?>
            <div class="right_col">
                <?php include '_breadcrumb.php';?>
                <div class="con_block">
                    <h3 class="con_title">商品API</h3>
                    <div class="con_main">
                      <h4 class="con_main_title">新增商品資訊</h4>
                      <h5 class="con_main_sub_title">用途</h5>
                      <p>購物平台在uitox系統新增商品資料。</p>
                      <h5 class="con_main_sub_title">串接方式</h5>
                      <p>採https網路協定，以POST方式串接實作。URL路徑提供如下：<br/>https://[uitox server name]/show_add/add_item</p>
                      <h5 class="con_main_sub_title">輸入參數、範例及說明</h5>
                      <p>HTTPS POST參數整理如下：</p>
                      <table class="con_table">
                            <thead>
                              <tr>
                                  <th>參數</th>
                                  <th>說明</th>
                                  <th>型別</th>
                                  <th>限制</th>
                                  <th>屬性</th>
                                  <th>備註</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>version</td>
                                    <td>版本</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>此API版本請填入1.0.0</td>
                                 </tr>
                                <tr>
                                    <td>client_id</td>
                                    <td>帳號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請聯繫uitox人員提供</td>
                                 </tr>
                                <tr>
                                    <td>token</td>
                                    <td>密碼</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請聯繫uitox人員提供</td>
                                 </tr>
                                <tr>
                                    <td>platform_id</td>
                                    <td>uitox平台編號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請聯繫uitox人員提供</td>
                                 </tr>
                                <tr>
                                    <td>cv</td>
                                    <td>檢查碼</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請參考檢查碼章節</td>
                                 </tr>
                                <tr>
                                    <td>data</td>
                                    <td>API參數字串</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>請聯繫uitox人員提供</td>
                                 </tr>
                            </tbody>
                         </table>
                         <p>請參考以下JSON字串範例：</p>
                          <code>
                            { <br/>
                              &nbsp;&nbsp;"client_id":"uitoxbeta",<br/>
                              &nbsp;&nbsp;"token":"qWerAsdf",<br/>
                              &nbsp;&nbsp;"platform_id":"AW000001",<br/>
                              &nbsp;&nbsp;"version":"1.0.0",<br/>
                              &nbsp;&nbsp;"cv":"0b139084d4aedcaaaeaf5047bae9b90b135e69041e446aa6d0ee0fa23f94ee2b",<br/>
                            }
                          </code>
                          <p>無規格商品的範例</p>
                          <code>
                            { <br/>
                              &nbsp;&nbsp;"client_id":"uitoxbeta",<br/>
                              &nbsp;&nbsp;"token":"qWerAsdf",<br/>
                              &nbsp;&nbsp;"platform_id":"AW000001",<br/>
                              &nbsp;&nbsp;"version":"1.0.0",<br/>
                              &nbsp;&nbsp;"cv":"0b139084d4aedcaaaeaf5047bae9b90b135e69041e446aa6d0ee0fa23f94ee2b",<br/>
                            }
                          </code>
                          <p>在 data 參數值這串 JSON 字串內，各參數說明如下：</p>
                          <table class="con_table">
                            <thead>
                              <tr>
                                  <th>參數</th>
                                  <th>說明</th>
                                  <th>型別</th>
                                  <th>限制</th>
                                  <th>屬性</th>
                                  <th>備註</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>status_code</td>
                                    <td>狀態代碼</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>請參考以下代碼表</td>
                                 </tr>
                                <tr>
                                    <td>access_token</td>
                                    <td>授權碼</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>token_type</td>
                                    <td>查詢狀態代碼</td>
                                    <td>String</td>
                                    <td></td>
                                    <td>必填</td>
                                    <td>用來識別API執行狀態</td>
                                 </tr>
                                <tr>
                                    <td>expires_in</td>
                                    <td>查詢日期</td>
                                    <td>String</td>
                                    <td>8</td>
                                    <td>必填</td>
                                    <td>格式YYYY/MM/DD</td>
                                 </tr>
                                <tr>
                                    <td>expires_on</td>
                                    <td>查詢時間</td>
                                    <td>String</td>
                                    <td>6</td>
                                    <td>必填</td>
                                    <td>格式HH:MM:SS</td>
                                 </tr>
                            </tbody>
                         </table>
                         <h5 class="con_main_sub_title">輸出回應、範例及說明</h5>
                         <p>API輸出回應的資料，一律放置在HTTPS協定回應結果的BODY區域，同樣以JSON格式輸出，請參考以下範例。</p>
                         <code>
                            { <br/>
                              &nbsp;&nbsp;"status_code":100,<br/>
                              &nbsp;&nbsp;"query_date":"2015/07/07",<br/>
                              &nbsp;&nbsp;"query_time":"12:00:00",<br/>
                              &nbsp;&nbsp;"count":3,<br/>
                              &nbsp;&nbsp;"failure":0,<br/>
                              &nbsp;&nbsp;"success":3,<br/>
                              &nbsp;&nbsp;"respone":<br/>
                            }
                          </code>
                          <p>在API輸出回應的這串JSON字串內，各參數說明如下</p>
                         <table class="con_table">
                            <thead>
                              <tr>
                                  <th>參數</th>
                                  <th>說明</th>
                                  <th>型別</th>
                                  <th>限制</th>
                                  <th>屬性</th>
                                  <th>備註</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>status_code</td>
                                    <td>狀態</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td>請參考以下代碼表</td>
                                 </tr>
                                <tr>
                                    <td>query_Date</td>
                                    <td>新增日期 yyyymmdd</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td>依照平台時間時區回覆</td>
                                 </tr>
                                <tr>
                                    <td>query_time</td>
                                    <td>新增時間hhmmss</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td>依照平台時間時區回覆</td>
                                 </tr>
                                <tr>
                                    <td>count</td>
                                    <td>新增總筆數</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>success</td>
                                    <td>成功筆數</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>failure</td>
                                    <td>失敗筆數</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/drc</td>
                                    <td>細項回應狀態</td>
                                    <td>Number</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/uitox_spec_id</td>
                                    <td>Uitox 規格編號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/supplier_spec_id</td>
                                    <td>廠商自訂規格編號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/uitox_spec_id</td>
                                    <td>Uitox 規格編號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                                <tr>
                                    <td>respone/spec/uitox_product_id</td>
                                    <td>uitox商品ID</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td>範例：201411AG12000001</td>
                                 </tr>
                                <tr>
                                    <td>respone/spec/own_product_id</td>
                                    <td>eShop廠商自用料號</td>
                                    <td>String</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                 </tr>
                            </tbody>
                         </table>
                         <h5 class="con_main_sub_title">使用建議</h5>
                         <p>一次執行最多100筆紀錄</p>
                         <h5 class="con_main_sub_title">代碼說明</h5>
                         <p>status_code參數</p>
                         <table class="con_table">
                            <thead>
                              <tr>
                                  <th>代碼</th>
                                  <th>說明</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>4002001100</td>
                                    <td>程式執行成功</td>
                                 </tr>
                                <tr>
                                    <td>4002001199</td>
                                    <td>筆數不符</td>
                                 </tr>
                                <tr>
                                    <td>4002001200</td>
                                    <td>傳入參數錯誤</td>
                                 </tr>
                                <tr>
                                    <td>4002001201</td>
                                    <td>傳入參數錯誤</td>
                                 </tr>
                                <tr>
                                    <td>4002001201</td>
                                    <td>傳入參數錯誤</td>
                                 </tr>
                                <tr>
                                    <td>4002001202</td>
                                    <td>傳入參數為空值</td>
                                 </tr>
                                <tr>
                                    <td>4002001203</td>
                                    <td>傳入參數型態錯誤</td>
                                 </tr>
                                <tr>
                                    <td>4002001204</td>
                                    <td>傳入參數長度錯誤</td>
                                 </tr>
                            </tbody>
                         </table>
                         <p>drc參數</p>
                         <table class="con_table">
                            <thead>
                              <tr>
                                  <th>代碼</th>
                                  <th>說明</th>
                              </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>100</td>
                                    <td>新增成功</td>
                                 </tr>
                                <tr>
                                    <td>199</td>
                                    <td>筆數不符合</td>
                                 </tr>
                                <tr>
                                    <td>201</td>
                                    <td>傳入API的參數錯誤</td>
                                 </tr>
                                <tr>
                                    <td>202</td>
                                    <td>傳入API的參數為空值</td>
                                 </tr>
                                <tr>
                                    <td>203</td>
                                    <td>傳入參數型態錯誤</td>
                                 </tr>
                                <tr>
                                    <td>204</td>
                                    <td>204 傳入參數長度錯誤</td>
                                 </tr>
                                <tr>
                                    <td>205</td>
                                    <td>品名必須一致</td>
                                 </tr>
                                <tr>
                                    <td>206</td>
                                    <td>保險價值必須一致</td>
                                 </tr>
                                <tr>
                                    <td>207</td>
                                    <td>廠商編號必須一致</td>
                                 </tr>
                                <tr>
                                    <td>208</td>
                                    <td>顏色/尺寸名稱不可重複</td>
                                 </tr>
                                <tr>
                                    <td>209</td>
                                    <td>多規格必須填寫顏色</td>
                                 </tr>
                                 <tr>
                                    <td>210</td>
                                    <td>每列必須填寫尺寸</td>
                                 </tr>
                                 <tr>
                                    <td>211</td>
                                    <td>每列必須填寫廠商自用料號</td>
                                 </tr>
                                 <tr>
                                    <td>212</td>
                                    <td>無廠商合約資訊</td>
                                 </tr>
                                 <tr>
                                    <td>213</td>
                                    <td>廠商自用料號必填</td>
                                 </tr>
                                 <tr>
                                    <td>214</td>
                                    <td>廠商自用料號重複</td>
                                 </tr>
                                 <tr>
                                    <td>215</td>
                                    <td>廠商自用料號格式錯誤</td>
                                 </tr>
                                 <tr>
                                    <td>216</td>
                                    <td>廠商自用欄位格式錯誤</td>
                                 </tr>
                                 <tr>
                                    <td>217</td>
                                    <td>特賣變價中，無法新增顏色/尺寸</td>
                                 </tr>
                                 <tr>
                                    <td>218</td>
                                    <td>圖片產生失敗</td>
                                 </tr>
                                 <tr>
                                    <td>219</td>
                                    <td>切圖失敗</td>
                                 </tr>
                                 <tr>
                                    <td>220</td>
                                    <td>新增失敗</td>
                                 </tr>
                            </tbody>
                         </table>
                    </div>
                </div>
            </div>
        </div>
<?php include '_footer.php';?>