<!-- Template list -->
<?php  
$siteMap = array(
    array(
        "name"      => "sth000",
        "url"       => "../sth_public/sth000/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth001",
        "url"       => "../sth_public/sth001/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth002",
        "url"       => "../sth_public/sth002/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
            "gold",
            "green",
            "purple",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth003",
        "url"       => "../sth_public/sth003/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
            "purple",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth004",
        "url"       => "../sth_public/sth004/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth005",
        "url"       => "../sth_public/sth005/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth006",
        "url"       => "../sth_public/sth006/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth007",
        "url"       => "../sth_public/sth007/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth008",
        "url"       => "../sth_public/sth008/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth009",
        "url"       => "../sth_public/sth009/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth010",
        "url"       => "../sth_public/sth010/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth011",
        "url"       => "../sth_public/sth011/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth012",
        "url"       => "../sth_public/sth012/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth013",
        "url"       => "../sth_public/sth013/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth014",
        "url"       => "../sth_public/sth014/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth015",
        "url"       => "../sth_public/sth015/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
            "gray",
            "pink",
            "black",
            "blue",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth_seagame",
        "url"       => "../sth_public/sth_seagame/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth_adi",
        "url"       => "../sth_public/sth_adi/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth_asap",
        "url"       => "../sth_public/sth_asap/index.php",
        // "state"     => "100",
        "color"     => array(
            "red",
            "purple",
            "green",
            "blue",
            "orange",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth_asap_m",
        "url"       => "../sth_public/sth_asap_m/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
        ),
        "desc"      => "",
    ),
    array(
        "name"      => "sth_sosoon",
        "url"       => "../sth_public/sth_sosoon/index.php",
        // "state"     => "100",
        "color"     => array(
            "white",
        ),
        "desc"      => "",
    ),
);
?>